import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative mx-auto select-none w-[100vw] md:w-[600px] h-[100dvh] overflow-scroll`}
      >
        <div className="containter">{children}</div>
      </body>
    </html>
  );
}
